### ISSUE TITLE
Why are S3 buckets not linked to much?

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/aws-source#282]
The S3 buckets in the example repo have only the following info:

```yaml
status: ''
name: replaceme-with-a-unique-bucket-name
grants:
- grantee:
    type: CanonicalUser
    id: 05d918fa182ad8f3fa915436354b8657e3c2c59b326ecbfc43e6c00451268d0a
  permission: FULL_CONTROL
mFADelete: ''
payer: BucketOwner
owner:
  id: 05d918fa182ad8f3fa915436354b8657e3c2c59b326ecbfc43e6c00451268d0a
ownershipControls:
  rules:
  - objectOwnership: BucketOwnerEnforced
locationConstraint: eu-west-2
```

There doesn't seem to be enough info to tie it to a URL or anything, though this should be possible
