### ISSUE TITLE
Not enough links for v2

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/aws-source#4]
Using a real ALB, I can get the followinf information:

```yaml
availabilityZones:
  - loadBalancerAddresses: []
    subnetId: subnet-156de64e
    zoneName: eu-west-1c
  - loadBalancerAddresses: []
    subnetId: subnet-6ff8a926
    zoneName: eu-west-1b
  - loadBalancerAddresses: []
    subnetId: subnet-b41d53d3
    zoneName: eu-west-1a
canonicalHostedZoneId: Z32O12XQLNTSW2
createdTime: 2021-12-21 13:36:26.23 +0000 UTC
dNSName: complete-alb-large-sloth-890937195.eu-west-1.elb.amazonaws.com
ipAddressType: ipv4
listeners:
  - certificates:
      - certificateArn: >-
          arn:aws:acm:eu-west-1:177828803798:certificate/b2988481-9b2b-464c-b6b9-3f710ea5477c
    defaultActions:
      - forwardConfig:
          targetGroupStickinessConfig:
            enabled: false
          targetGroups:
            - targetGroupArn: >-
                arn:aws:elasticloadbalancing:eu-west-1:177828803798:targetgroup/h120211221133637410300000004/d4edb1d84fb0dadc
              weight: 1
        order: 1
        targetGroupArn: >-
          arn:aws:elasticloadbalancing:eu-west-1:177828803798:targetgroup/h120211221133637410300000004/d4edb1d84fb0dadc
        type: forward
    listenerArn: >-
      arn:aws:elasticloadbalancing:eu-west-1:177828803798:listener/app/complete-alb-large-sloth/6a70f548a17bf6ed/04027421285f3de8
    loadBalancerArn: >-
      arn:aws:elasticloadbalancing:eu-west-1:177828803798:loadbalancer/app/complete-alb-large-sloth/6a70f548a17bf6ed
    port: 443
    protocol: HTTPS
    sslPolicy: ELBSecurityPolicy-2016-08
  - defaultActions:
      - forwardConfig:
          targetGroupStickinessConfig:
            enabled: false
          targetGroups:
            - targetGroupArn: >-
                arn:aws:elasticloadbalancing:eu-west-1:177828803798:targetgroup/h120211221133637410300000004/d4edb1d84fb0dadc
              weight: 1
        order: 1
        targetGroupArn: >-
          arn:aws:elasticloadbalancing:eu-west-1:177828803798:targetgroup/h120211221133637410300000004/d4edb1d84fb0dadc
        type: forward
    listenerArn: >-
      arn:aws:elasticloadbalancing:eu-west-1:177828803798:listener/app/complete-alb-large-sloth/6a70f548a17bf6ed/302b9e60c3bb9953
    loadBalancerArn: >-
      arn:aws:elasticloadbalancing:eu-west-1:177828803798:loadbalancer/app/complete-alb-large-sloth/6a70f548a17bf6ed
    port: 80
    protocol: HTTP
loadBalancerArn: >-
  arn:aws:elasticloadbalancing:eu-west-1:177828803798:loadbalancer/app/complete-alb-large-sloth/6a70f548a17bf6ed
name: complete-alb-large-sloth
scheme: internet-facing
securityGroups:
  - sg-0b57e125c21f784b9
state:
  code: active
targetGroups:
  - healthCheckEnabled: true
    healthCheckIntervalSeconds: 30
    healthCheckPath: /api/health
    healthCheckPort: '8080'
    healthCheckProtocol: HTTP
    healthCheckTimeoutSeconds: 6
    healthyThresholdCount: 3
    ipAddressType: ipv4
    loadBalancerArns:
      - >-
        arn:aws:elasticloadbalancing:eu-west-1:177828803798:loadbalancer/app/complete-alb-large-sloth/6a70f548a17bf6ed
    matcher:
      httpCode: 200-399
    port: 8080
    protocol: HTTP
    protocolVersion: HTTP1
    targetGroupArn: >-
      arn:aws:elasticloadbalancing:eu-west-1:177828803798:targetgroup/h120211221133637410300000004/d4edb1d84fb0dadc
    targetGroupName: h120211221133637410300000004
    targetHealthDescriptions:
      - healthCheckPort: '8080'
        target:
          id: i-00062af477c9160b8
          port: 8080
        targetHealth:
          reason: ''
          state: healthy
    targetType: instance
    unhealthyThresholdCount: 3
    vpcId: vpc-5088d537
type: application
vpcId: vpc-5088d537
```

However the only linked items this has is those to a DNS name. I need to work out how to link to the other relevant stuff, especially the targets
